# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Grocery-App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Grocery-App
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Messaging'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  pod 'Firebase/Database'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/InAppMessaging'
  pod 'SDWebImageSwiftUI'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/RemoteConfig'
end
